<a href="https://colab.research.google.com/github/SadFill/Gauss-s-method/blob/main/goose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [114]:
# generates matrix'es dimensionarity 

dim = np.random.randint(1,5) 

# generates a matrix with size(dim, dim+1)

mat = np.random.randint(0,10, size=(dim,dim+1)).astype('float64')

In [115]:
def printer(data):
  print(data)

printer(mat)

[[9. 2. 3. 1. 7.]
 [3. 5. 1. 8. 5.]
 [7. 6. 4. 0. 9.]
 [6. 6. 4. 3. 6.]]


In [ ]:
# def find_min_element(mat):
  
#   """finds min values in each column
#   """
#   for row in mat:
#     for column in mat:
#       min = np.min(mat, axis=0)
#   return min

In [110]:
# def to_ones(mat):
#   """
#   converts original matrix to identity matrix
#   """
#   for row in range(dim):
#     if mat[row,row] ==0:
#       continue
#     matrix = mat[row,:] = mat[row,:]/mat[row,row]
#   return matrix


In [111]:
to_ones(mat)
print(mat)

[[1.         0.         0.66666667 2.33333333 1.33333333]
 [2.         1.         0.66666667 0.66666667 2.33333333]
 [1.75       0.25       1.         1.         0.        ]
 [0.66666667 1.33333333 3.         1.         0.        ]]


In [97]:
mat

array([[1.        , 1.        , 2.5       , 1.        , 2.5       ],
       [0.        , 1.        , 0.125     , 1.125     , 0.375     ],
       [1.        , 3.        , 1.        , 1.66666667, 2.33333333],
       [3.5       , 4.5       , 3.        , 1.        , 2.5       ]])

In [117]:
def to_triangle(mat):
    """
  converts identity matrix to triangle matrix
    """
    for row in range(dim):
      mat[row,:] = mat[row,:]/mat[row,row]
      for column in range(row+1, dim):
        if mat[column,row] !=0:
          mat[column,:] = mat[column,:]-mat[column,:] * mat[row,:]
    return mat

In [118]:
printer(to_triangle(mat))

[[ 1.          0.22222222  0.33333333  0.11111111  0.77777778]
 [ 0.          1.          0.17142857  1.82857143  0.28571429]
 [ 0.          0.          1.          0.          0.64655172]
 [-0.         -0.         -0.          1.         -0.15234839]]


## **Извините, всё!**

In [ ]:
def findmin(mat):
  for row in mat[-1,:]:
    min = np.min(mat, axis=0)
  return min

In [79]:
# findmin(mat)

array([ 0.        ,  0.        , -4.5       ,  0.03636364,  0.12272727])

In [ ]:
# # finds min in 1-st column
minimum = np.min(mat[:,0])
minimum

nan

In [ ]:
# делим последнюю строку на минимум
mat[-1,:] = (mat[-1,:]/minimum)
mat

array([[1. , 0.4, 1.6],
       [nan, nan, nan]])