<a href="https://colab.research.google.com/github/SadFill/Gauss-s-method/blob/main/goose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
dim = np.random.randint(1,5)
mat = np.random.randint(0,10, size=(dim,dim)).astype('float64')

In [ ]:
def printer(data):
  print(data)

printer(mat)

[[8. 2.]
 [6. 5.]]


In [ ]:
def find_min_element(mat):
  
  """finds min values in each column
  """
  for row in mat:
    for column in mat:
      min = np.min(mat, axis=0)
  return min

In [ ]:
find_min_element(mat)

array([6., 2.])

In [ ]:
def to_zero(mat):
    for row in mat:
      for column in mat:
        min = np.min(mat, axis=0) >0 #находим минимальный элемент

  #     for element in mat[min]:
  #       mat[min] = mat[min]/min
  # return min

In [ ]:
def findmin(mat):
  for row in mat[-1,:]:
    min = np.min(mat, axis=0)
  return min

In [ ]:
findmin(mat)

array([6., 2.])

In [ ]:
# finds min in 1-st column
minimum = np.min(mat[:,0])
minimum

6.0

In [ ]:
# делим последнюю строку на минимум
mat[-1,:] = (mat[-1,:]/minimum)
mat

array([[8.        , 2.        ],
       [1.        , 0.83333333]])

In [ ]:
for raw in reversed(mat):
  print(raw)

2.0
8.0
